# from container.yml file
# name of workflow
name: deploy-container

# on === add event listener
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

  # for push event
  push:
    # on the following array of branches
    branches:
      - main
      - master
    # only run this workflow when we make a change to any of the following
    paths:
      # any (**) change inside the container dir
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #    - uses: actions/checkout@v2
      - uses: shinyinc/action-aws-cli@v1.2
      - run: npm run install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
